# Generated by Django 4.1rc1 on 2022-07-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_book_favorited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="title_page",
            field=models.ImageField(blank=True, null=True, upload_to="title_pages"),
        ),
    ]
